#**The Weather Dataset**


---
Here, The  Weather Dataset is a time-senes data set with per-hour information about the weather conditions at a particular location. it records Temperature, Dew Point Temperature, Relative Humidity, Wind Speed, Visibility, Pressure, and Conditions.

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_excel("/content/drive/MyDrive/principle of data science/whether.xlsx")

In [ ]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

# **How to Analyze Dataframes?**

#**.head()**

it shows the first N rows in the data(by default, N=5).

In [ ]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

#**.shape**

it shows the total no.of rows and no.of columns of the dataframe.

In [ ]:
data.shape

(8784, 8)

#**.index**

This attribute provides the index of the dataframe.

In [ ]:
data.index

RangeIndex(start=0, stop=8784, step=1)

#**.columns**

it shows the name of each coulmn.

In [ ]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

#**.dtypes**

it shows the data-type of each column.

In [ ]:
data.dtypes

Date/Time           datetime64[ns]
Temp_C                     float64
Dew Point Temp_C           float64
Rel Hum_%                    int64
Wind Speed_km/h              int64
Visibility_km              float64
Press_kPa                  float64
Weather                     object
dtype: object

#**.unique()**

In a column, it shows all the  unique values. it can be applied on a single column as well as on whole dataframe.

In [ ]:
data["Weather"].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

#**.nunique()**

It shows the total no.of unique values in each column.It can be applied on a single column as well as on a whole dataframe.

In [ ]:
data["Weather"].nunique()

50

#**.count**

It shows the total no.of non-null in each column. It can be applied on a single column as well as on whole dataframe.

In [ ]:
data.count()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

#**.value_counts**

In a column, it shows all the unique values with their count. It can be applied on single column only.

In [ ]:
data["Weather"].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

#**.info()**

Provides basic information about the dataframe.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   datetime64[ns]
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

#**Q)1.Find all the unique "Wind speed" values in the data.**

In [ ]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [ ]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

In [ ]:
data["Wind Speed_km/h"].nunique()

34

In [ ]:
data["Wind Speed_km/h"].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

#**Q)2.Find the number of times when the "Weather is exactly Clear".**

In [ ]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

In [ ]:
data.Weather.value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [ ]:
#data.head(2)
data[data.Weather=="Clear"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [ ]:
#groupby()
#data.head(2)
data.groupby("Weather").get_group("Clear")

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

#**Q)3.Find the number of times when the "Wind Speed was exactly 4 km/h".**

In [ ]:
data[data["Wind Speed_km/h"]==4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,2012-01-05 00:00:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,2012-01-05 05:00:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,2012-01-07 02:00:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,2012-12-31 08:00:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,2012-12-31 09:00:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,2012-12-31 10:00:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,2012-12-31 12:00:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,2012-12-31 13:00:00,-4.6,-6.6,86,4,12.9,100.63,Snow

#**Q)4.Find the Null Values in the data.**

In [ ]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [ ]:
data.notnull().sum()

Date/Time           8784
Temp_C              8784
Dew Point Temp_C    8784
Rel Hum_%           8784
Wind Speed_km/h     8784
Visibility_km       8784
Press_kPa           8784
Weather             8784
dtype: int64

#**Q)5.Rename the column name "Weather" of the dataframe to "Weather condition".**

In [ ]:
data.rename(columns={"Weather":"Weather condition"},inplace=True)

In [ ]:
data.head(2)

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog

#**Q)6.What is the mean of "Visibility"?.**

In [ ]:
data['Visibility_km'].mean()

27.664446721311478

#**Q)7. What is the Standard Deviation of "pressure" in this data?**

In [ ]:
data['Press_kPa'].std()

0.8440047459486474

#**Q)8.What is the Variance of "Relative Humidity"in this data?.**

In [ ]:
data['Rel Hum_%'].var()

286.2485501984998

#**Q)9.Find all instances when "Snow" was recorded**

In [ ]:
#value_counts
data['Weather condition'].value_counts()

Weather condition
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [ ]:
#filtering
data[data["Weather condition"]=="Snow"]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [ ]:
#str.contains
data[data["Weather condition"].str.contains("Snow")]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

#**Q)10.Find all the instances with "Wind Speedis above 24" and "Visibility is 25"**

In [ ]:
data[(data['Wind Speed_km/h'] > 40) & (data['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
409,2012-01-18 01:00:00,3.7,-2.1,66,83,25.0,98.36,Mostly Cloudy
410,2012-01-18 02:00:00,0.5,-4.0,72,70,25.0,98.62,Mostly Cloudy
411,2012-01-18 03:00:00,-3.5,-8.2,70,57,25.0,99.00,Mostly Cloudy
412,2012-01-18 04:00:00,-6.1,-10.9,69,48,25.0,99.36,Snow
557,2012-01-24 05:00:00,3.7,-0.2,76,41,25.0,100.37,Cloudy
672,2012-01-29 00:00:00,1.5,-5.0,62,57,25.0,99.96,Mainly Clear
673,2012-01-29 01:00:00,0.9,-5.3,63,52,25.0,100.09,Mainly Clear
674,2012-01-29 02:00:00,0.3,-5.8,64,52,25.0,100.21,Mainly Clear
675,2012-01-29 03:00:00,-0.2,-6.0,65,43,25.0,100.34,Mainly Clear
676,2012-01-29 04:00:00,-0.9,-7.0,63,43,25.0,100.47,Mainly Clear
677,2012-01-29 05:00:00,-1.5,-7.8,62,43,25.0,100.59,Mainly Clear
678,2012-01-29 06:00:00,-2.0,-8.1,63,44,25.0,100.68,Mainly Clear
1494,2012-03-03 06:00:00,1.5,-1.6,80,43,25.0,99.02,Mainly Clear
1506,2012-03-03 18:00:00,3.7,-4.3,56,48,25.0,98.82,Mostly Cloudy
1507,2012-03-03 19:00:00,3.4,-4.0,58,44,25.0,98.92,Mainly Clear
1508,2012-03-03 20:00:00,3.2,-3.9,60,50,25.0,98.96,Mainly Clear
1509,2012-03-03 21:00:00,2.9,-3.6,62,46,25.0,98.98,Snow
1510,2012-03-03 22:00:00,2.8,-3.4,64,57,25.0,99.07,Snow
1628,2012-03-08 20:00:00,5.0,1.6,79,41,25.0,99.90,Rain
2714,2012-04-23 02:00:00,1.1,-1.1,85,44,25.0,100.32,"Rain,Snow"
2715,2012-04-23 03:00:00,1.7,-0.7,84,52,25.0,100.11,"Rain,Snow"
2716,2012-04-23 04:00:00,2.0,-0.7,82,44,25.0,99.82,Rain
2732,2012-04-23 20:00:00,5.7,3.6,86,41,25.0,98.54,Cloudy
5827,2012-08-30 19:00:00,25.5,16.3,57,43,25.0,100.49,Mostly Cloudy
5829,2012-08-30 21:00:00,24.5,15.6,58,44,25.0,100.53,Mainly Clear
5830,2012-08-30 22:00:00,24.2,15.5,58,41,25.0,100.54,Mainly Clear
6044,2012-09-08 20:00:00,19.2,13.2,68,43,25.0,99.51,Mainly Clear
6045,2012-09-08 21:00:00,16.1,12.7,80,44,25.0,99.67,Mostly Cloudy
7266,2012-10-29 18:00:00,14.2,9.2,72,44,25.0,99.83,Mostly Cloudy
7267,2012-10-29 19:00:00,14.0,9.6,75,50,25.0,99.65,Mostly Cloudy
7268,2012-10-29 20:00:00,14.3,9.7,74,52,25.0,99.55,Cloudy
7269,2012-10-29 21:00:00,14.0,9.7,75,48,25.0,99.46,Mostly Cloudy
7270,2012-10-29 22:00:00,14.2,9.8,75,50,25.0,99.37,Cloudy
7271,2012-10-29 23:00:00,14.1,10.0,76,54,25.0,99.33,Cloudy
7272,2012-10-30 00:00:00,14.6,10.2,75,41,25.0,99.28,Cloudy
7273,2012-10-30 01:00:00,14.6,10.4,76,52,25.0,99.23,Mostly Cloudy
7275,2012-10-30 03:00:00,13.9,10.6,80,41,25.0,99.21,Rain Showers
7608,2012-11-13 00:00:00,14.8,10.0,73,48,25.0,100.94,Rain
7611,2012-11-13 03:00:00,7.9,5.6,85,41,25.0,101.45,Rain
8538,2012-12-21 18:00:00,1.4,0.3,92,46,25.0,97.56,Rain

#**Q)11.What is the Mean value of each column against each "Weather Condition"**

In [ ]:
data.groupby("Weather condition").mean()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather condition,,,,,,,
Clear,2012-06-25 18:03:12.760180992,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,2012-07-01 16:51:29.583333376,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,2012-09-17 15:00:00.000000000,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",2012-06-30 00:44:15.000000000,8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00.000000000,0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",2012-12-18 16:30:00.000000000,1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",2012-12-19 20:56:00.000000000,0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,2012-06-24 21:08:00.000000000,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,2012-03-05 23:25:42.857142784,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",2012-04-30 06:20:00.000000000,-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",2012-02-01 12:00:00.000000000,-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",2012-06-27 12:32:43.636363520,-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,2012-02-22 06:45:00.000000000,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,2012-02-14 01:34:17.142857216,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",2012-06-28 15:45:00.000000000,-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",2012-02-01 14:30:00.000000000,-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",2012-12-17 03:00:00.000000000,-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",2012-01-13 09:00:00.000000000,-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,2012-06-06 00:37:30.000000000,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,2012-07-12 06:48:08.888888832,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",2012-12-10 08:00:00.000000000,1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,2012-07-05 12:00:00.000000000,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",2012-12-27 11:00:00.000000000,-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,2012-07-01 10:42:53.417109760,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,2012-07-02 07:18:02.352941056,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,2012-07-14 17:25:51.063829760,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",2012-10-20 03:00:00.000000000,12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2012-11-19 21:00:00.000000000,2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",2012-08-17 05:19:08.275862016,8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",2012-03-13 08:00:00.000000000,4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",2012-12-18 05:00:00.000000000,0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",2012-07-22 00:23:20.000000000,1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",2012-12-21 00:00:00.000000000,1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",2012-12-08 21:00:00.000000000,0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",2012-12-21 03:15:00.000000000,1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,2012-04-18 19:10:36.923076864,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,2012-11-24 15:00:00.000000000,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,2012-07-21 22:40:59.999999744,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",2012-12-28 17:15:00.000000000,-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",2012-08-08 17:44:12.631578880,-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",2012-10-21 17:42:09.729729792,-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",2012-02-01 19:00:00.000000000,-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",2012-09-14 21:00:00.000000000,-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,2012-07-10 08:30:00.000000000,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",2012-05-29 06:00:00.000000000,10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",2012-07-17 06:00:00.000000000,19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",2012-07-04 02:20:00.000000000,20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",2012-07-18 14:48:45.000000000,20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",2012-07-16 02:40:00.000000000,21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",2012-07-17 05:00:00.000000000,20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

#**Q)12.What is the Minimum & Maximum value of each column against each "Weather Condition"?**

In [ ]:
data.groupby("Weather condition").min()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather condition,,,,,,,
Clear,2012-01-03 19:00:00,-23.3,-28.5,20,0,11.3,99.52
Cloudy,2012-01-01 17:00:00,-21.4,-26.8,18,0,11.3,98.39
Drizzle,2012-01-23 21:00:00,1.1,-0.2,74,0,6.4,97.84
"Drizzle,Fog",2012-01-23 20:00:00,0.0,-1.6,85,0,1.0,98.65
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",2012-12-17 15:00:00,0.9,0.1,92,9,9.7,100.63
"Drizzle,Snow,Fog",2012-12-18 21:00:00,0.3,-0.1,92,7,2.4,97.79
Fog,2012-01-01 00:00:00,-16.0,-17.2,80,0,0.2,98.31
Freezing Drizzle,2012-01-07 11:00:00,-9.0,-12.2,78,6,4.8,98.44
"Freezing Drizzle,Fog",2012-01-01 02:00:00,-6.4,-9.0,82,6,3.6,98.74
"Freezing Drizzle,Haze",2012-02-01 11:00:00,-5.8,-8.3,81,9,2.0,100.28
"Freezing Drizzle,Snow",2012-01-13 03:00:00,-8.3,-10.4,79,6,2.4,99.19
Freezing Fog,2012-01-22 06:00:00,-19.0,-22.9,71,0,0.2,101.97
Freezing Rain,2012-01-07 10:00:00,-6.5,-9.0,81,7,2.8,98.22
"Freezing Rain,Fog",2012-01-07 09:00:00,-6.1,-8.7,82,7,2.8,98.32
"Freezing Rain,Haze",2012-02-01 14:00:00,-4.9,-7.5,82,6,2.0,100.34
"Freezing Rain,Ice Pellets,Fog",2012-12-17 03:00:00,-2.6,-3.7,92,28,8.0,100.95
"Freezing Rain,Snow Grains",2012-01-13 09:00:00,-5.0,-7.3,84,32,4.8,98.56
Haze,2012-01-22 12:00:00,-11.5,-16.0,68,0,4.8,100.35
Mainly Clear,2012-01-02 12:00:00,-22.8,-28.0,20,0,12.9,98.67
"Moderate Rain,Fog",2012-12-10 08:00:00,1.7,0.8,94,17,6.4,99.98
Moderate Snow,2012-01-12 15:00:00,-6.3,-7.6,83,26,0.6,99.88
"Moderate Snow,Blowing Snow",2012-12-27 10:00:00,-5.5,-6.6,92,39,0.6,100.50
Mostly Cloudy,2012-01-01 16:00:00,-23.2,-28.5,18,0,11.3,98.36
Rain,2012-01-01 18:00:00,0.3,-5.7,40,0,4.0,97.52
Rain Showers,2012-01-01 22:00:00,1.6,-7.2,37,0,6.4,98.51
"Rain Showers,Fog",2012-10-20 03:00:00,12.8,12.1,96,13,6.4,99.83
"Rain Showers,Snow Showers",2012-11-04 08:00:00,2.1,-1.8,75,17,19.3,101.09
"Rain,Fog",2012-01-23 18:00:00,0.0,-1.2,83,0,2.0,98.61
"Rain,Haze",2012-03-13 07:00:00,4.0,1.0,81,7,4.0,100.50
"Rain,Ice Pellets",2012-12-18 05:00:00,0.6,-0.6,92,24,9.7,100.12
"Rain,Snow",2012-01-10 05:00:00,0.6,-1.7,81,13,2.4,98.18
"Rain,Snow Grains",2012-12-21 00:00:00,1.9,-2.1,75,26,25.0,100.60
"Rain,Snow,Fog",2012-12-08 21:00:00,0.8,0.3,96,9,6.4,100.73
"Rain,Snow,Ice Pellets",2012-12-21 01:00:00,0.9,-0.7,88,17,4.8,99.85
Snow,2012-01-03 07:00:00,-16.7,-24.6,41,0,1.0,97.75
Snow Pellets,2012-11-24 15:00:00,0.7,-6.4,59,35,2.4,99.70
Snow Showers,2012-01-02 17:00:00,-13.3,-19.3,52,0,2.4,99.49
"Snow Showers,Fog",2012-12-26 09:00:00,-11.3,-12.7,89,7,4.0,100.63
"Snow,Blowing Snow",2012-01-13 21:00:00,-12.0,-16.2,70,24,0.6,98.11
"Snow,Fog",2012-02-10 23:00:00,-10.1,-12.0,77,4,1.2,99.38
"Snow,Haze",2012-02-01 17:00:00,-4.3,-7.2,80,0,4.0,100.61
"Snow,Ice Pellets",2012-03-03 04:00:00,-4.3,-5.9,76,19,2.8,99.40
Thunderstorms,2012-07-04 16:00:00,21.6,19.4,67,0,24.1,99.84
"Thunderstorms,Heavy Rain Showers",2012-05-29 06:00:00,10.9,9.0,88,9,2.4,100.26
"Thunderstorms,Moderate Rain Showers,Fog",2012-07-17 06:00:00,19.6,18.5,93,15,3.2,100.01
"Thunderstorms,Rain",2012-05-25 20:00:00,19.4,18.2,83,4,16.1,100.19
"Thunderstorms,Rain Showers",2012-05-29 04:00:00,11.0,7.0,68,7,6.4,99.65
"Thunderstorms,Rain Showers,Fog",2012-06-29 03:00:00,19.5,16.1,80,7,9.7,99.71
"Thunderstorms,Rain,Fog",2012-07-17 05:00:00,20.6,18.6,88,19,4.8,100.08

In [ ]:
 data.groupby("Weather condition").max()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather condition,,,,,,,
Clear,2012-12-30 20:00:00,32.8,20.4,99,33,48.3,103.63
Cloudy,2012-12-31 06:00:00,30.5,22.6,99,54,48.3,103.65
Drizzle,2012-12-22 01:00:00,18.8,17.7,96,30,25.0,101.56
"Drizzle,Fog",2012-12-19 10:00:00,19.9,19.1,100,28,9.7,102.07
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00,0.4,-0.7,92,20,4.0,100.79
"Drizzle,Snow",2012-12-19 18:00:00,1.2,0.2,95,19,11.3,101.15
"Drizzle,Snow,Fog",2012-12-22 03:00:00,1.1,0.6,98,32,9.7,100.15
Fog,2012-12-29 10:00:00,20.8,19.6,100,22,9.7,103.04
Freezing Drizzle,2012-12-17 00:00:00,-2.3,-3.3,93,26,12.9,101.02
"Freezing Drizzle,Fog",2012-12-10 05:00:00,-0.3,-2.3,94,33,8.0,101.27
"Freezing Drizzle,Haze",2012-02-01 13:00:00,-5.0,-7.7,83,11,4.0,100.36
"Freezing Drizzle,Snow",2012-12-28 02:00:00,-3.3,-4.6,94,24,12.9,101.18
Freezing Fog,2012-03-17 06:00:00,-0.1,-0.3,99,9,0.8,102.85
Freezing Rain,2012-12-17 02:00:00,0.3,-1.7,92,28,16.1,101.00
"Freezing Rain,Fog",2012-12-17 01:00:00,0.1,-0.9,93,26,9.7,101.01
"Freezing Rain,Haze",2012-02-01 15:00:00,-4.9,-7.4,83,9,2.8,100.41
"Freezing Rain,Ice Pellets,Fog",2012-12-17 03:00:00,-2.6,-3.7,92,28,8.0,100.95
"Freezing Rain,Snow Grains",2012-01-13 09:00:00,-5.0,-7.3,84,32,4.8,98.56
Haze,2012-12-13 12:00:00,14.1,11.1,86,17,9.7,102.97
Mainly Clear,2012-12-30 22:00:00,33.0,21.2,99,63,48.3,103.59
"Moderate Rain,Fog",2012-12-10 08:00:00,1.7,0.8,94,17,6.4,99.98
Moderate Snow,2012-12-27 09:00:00,-4.9,-6.7,93,39,0.8,100.67
"Moderate Snow,Blowing Snow",2012-12-27 12:00:00,-5.4,-6.4,93,41,0.6,100.64
Mostly Cloudy,2012-12-31 03:00:00,32.4,24.4,100,83,48.3,103.65
Rain,2012-12-21 21:00:00,22.8,20.4,99,52,48.3,102.26
Rain Showers,2012-12-14 11:00:00,26.4,23.0,97,41,48.3,102.31
"Rain Showers,Fog",2012-10-20 03:00:00,12.8,12.1,96,13,6.4,99.83
"Rain Showers,Snow Showers",2012-12-05 10:00:00,2.2,-1.2,78,28,24.1,101.11
"Rain,Fog",2012-12-10 17:00:00,21.7,19.5,100,46,9.7,101.77
"Rain,Haze",2012-03-13 09:00:00,5.5,2.9,86,17,9.7,100.61
"Rain,Ice Pellets",2012-12-18 05:00:00,0.6,-0.6,92,24,9.7,100.12
"Rain,Snow",2012-12-21 09:00:00,1.7,0.5,94,52,25.0,101.07
"Rain,Snow Grains",2012-12-21 00:00:00,1.9,-2.1,75,26,25.0,100.60
"Rain,Snow,Fog",2012-12-08 21:00:00,0.8,0.3,96,9,6.4,100.73
"Rain,Snow,Ice Pellets",2012-12-21 05:00:00,1.3,0.1,94,28,6.4,100.47
Snow,2012-12-31 23:00:00,3.7,0.3,96,57,25.0,102.73
Snow Pellets,2012-11-24 15:00:00,0.7,-6.4,59,35,2.4,99.70
Snow Showers,2012-12-31 08:00:00,2.9,-0.7,94,37,48.3,102.50
"Snow Showers,Fog",2012-12-29 13:00:00,-10.0,-11.1,92,22,9.7,102.52
"Snow,Blowing Snow",2012-12-27 19:00:00,-1.4,-2.9,91,48,9.7,100.62
"Snow,Fog",2012-12-31 10:00:00,1.1,0.8,99,35,9.7,102.07
"Snow,Haze",2012-02-01 21:00:00,-3.6,-6.4,81,15,6.4,100.99
"Snow,Ice Pellets",2012-12-17 06:00:00,0.8,-1.7,92,33,11.3,100.96
Thunderstorms,2012-07-16 01:00:00,26.7,20.1,87,15,25.0,100.62
"Thunderstorms,Heavy Rain Showers",2012-05-29 06:00:00,10.9,9.0,88,9,2.4,100.26
"Thunderstorms,Moderate Rain Showers,Fog",2012-07-17 06:00:00,19.6,18.5,93,15,3.2,100.01
"Thunderstorms,Rain",2012-07-23 18:00:00,21.3,19.1,93,30,24.1,100.83
"Thunderstorms,Rain Showers",2012-09-14 20:00:00,25.5,23.1,98,32,25.0,101.06
"Thunderstorms,Rain Showers,Fog",2012-07-31 20:00:00,22.9,21.3,91,35,9.7,100.64
"Thunderstorms,Rain,Fog",2012-07-17 05:00:00,20.6,18.6,88,19,4.8,100.08

#**Q)13.Show all the Records where Weather Condition is Fog**

In [ ]:
data[data['Weather condition']=='Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,2012-12-29 04:00:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,2012-12-29 05:00:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,2012-12-29 06:00:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,2012-12-29 07:00:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,2012-12-29 10:00:00,-12.0,-13.3,90,7,6.4,101.15,Fog

#**Q)14. Find all instances when "Weather is Clear" or"Visibility is above 40'.**

In [ ]:
data[(data['Weather condition']=='Clear' ) | (data['Visibility_km']>40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
67,2012-01-03 19:00:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear

#**Q)15. Find all instaces when:**

**A. 'Weather is Clear'and 'Realtive Humidity is greater than50'**

#**or**

**B.'Visibility is above 40'**

In [ ]:
data[(data['Weather condition']=='Clear') & (data['Rel Hum_%']>50) | (data['Visibility_km']>40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather condition
106,2012-01-05 10:00:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,2012-01-05 11:00:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,2012-01-05 12:00:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,2012-01-05 13:00:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,2012-01-05 14:00:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,2012-12-30 13:00:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,2012-12-30 14:00:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,2012-12-30 15:00:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,2012-12-30 16:00:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear